/* Generated by Yosys 0.26+4 (git sha1 5ea2c290a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module PWM_gen(clk, increase_duty, decrease_duty, reset, PWM_OUT, OUT_CLK);
  wire [3:0] _000_;
  wire [27:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire [3:0] _316_;
  wire [3:0] _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire [3:0] DUTY_CYCLE;
  output OUT_CLK;
  wire OUT_CLK;
  output PWM_OUT;
  wire PWM_OUT;
  input clk;
  wire clk;
  wire [3:0] counter_PWM;
  wire [27:0] counter_debounce;
  input decrease_duty;
  wire decrease_duty;
  input increase_duty;
  wire increase_duty;
  input reset;
  wire reset;
  wire slow_clk_enable;
  wire tmp1;
  wire tmp2;
  wire tmp3;
  wire tmp4;
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(_315_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(_234_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__clkinv_1 _329_ (
    .A(_236_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__clkinv_1 _330_ (
    .A(_235_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__clkinv_1 _331_ (
    .A(_311_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__or2_0 _332_ (
    .A(_258_),
    .B(_257_),
    .X(_303_)
  );
  sky130_fd_sc_hd__or4_1 _333_ (
    .A(_262_),
    .B(_261_),
    .C(_241_),
    .D(_240_),
    .X(_304_)
  );
  sky130_fd_sc_hd__nor4_1 _334_ (
    .A(_254_),
    .B(_253_),
    .C(_256_),
    .D(_255_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nor4_1 _335_ (
    .A(_245_),
    .B(_244_),
    .C(_249_),
    .D(_250_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_305_),
    .B(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__or3_1 _337_ (
    .A(_303_),
    .B(_304_),
    .C(_307_),
    .X(_308_)
  );
  sky130_fd_sc_hd__nor4_1 _338_ (
    .A(_246_),
    .B(_247_),
    .C(_252_),
    .D(_251_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor4_1 _339_ (
    .A(_239_),
    .B(_238_),
    .C(_243_),
    .D(_242_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(_309_),
    .B(_310_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nor3_1 _341_ (
    .A(_259_),
    .B(_260_),
    .C(_264_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(_248_),
    .B(_263_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand3_1 _343_ (
    .A(_237_),
    .B(_268_),
    .C(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_268_),
    .B(_269_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor4_1 _345_ (
    .A(_259_),
    .B(_260_),
    .C(_264_),
    .D(_263_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor2b_1 _346_ (
    .A(_248_),
    .B_N(_237_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__nand4_1 _347_ (
    .A(_309_),
    .B(_310_),
    .C(_272_),
    .D(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor4b_1 _348_ (
    .A(_308_),
    .B(_267_),
    .C(_271_),
    .D_N(_270_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(_233_),
    .B(_234_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21oi_1 _350_ (
    .A1(_302_),
    .A2(_275_),
    .B1(_301_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(_233_),
    .B(_276_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__and2_0 _352_ (
    .A(_233_),
    .B(_234_),
    .X(_277_)
  );
  sky130_fd_sc_hd__nor3_1 _353_ (
    .A(_236_),
    .B(_275_),
    .C(_277_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _354_ (
    .A1(_235_),
    .A2(_277_),
    .B1(_236_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__o21a_1 _355_ (
    .A1(_235_),
    .A2(_277_),
    .B1(_278_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(_276_),
    .B(_278_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2b_1 _357_ (
    .A(_233_),
    .B_N(_219_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__maj3_1 _358_ (
    .A(_220_),
    .B(_300_),
    .C(_279_),
    .X(_280_)
  );
  sky130_fd_sc_hd__maj3_1 _359_ (
    .A(_221_),
    .B(_302_),
    .C(_280_),
    .X(_281_)
  );
  sky130_fd_sc_hd__maj3_1 _360_ (
    .A(_222_),
    .B(_301_),
    .C(_281_),
    .X(_223_)
  );
  sky130_fd_sc_hd__or2_0 _361_ (
    .A(_220_),
    .B(_221_),
    .X(_282_)
  );
  sky130_fd_sc_hd__a21oi_1 _362_ (
    .A1(_222_),
    .A2(_282_),
    .B1(_313_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nor3_1 _363_ (
    .A(_308_),
    .B(_267_),
    .C(_270_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(_314_),
    .B(_284_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nor3_1 _365_ (
    .A(_219_),
    .B(_222_),
    .C(_282_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__nor3_1 _366_ (
    .A(_315_),
    .B(_285_),
    .C(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__a31oi_1 _367_ (
    .A1(_312_),
    .A2(_283_),
    .A3(_284_),
    .B1(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__nor4_1 _368_ (
    .A(_303_),
    .B(_304_),
    .C(_307_),
    .D(_274_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nand3_1 _369_ (
    .A(_312_),
    .B(_283_),
    .C(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__xnor2_1 _370_ (
    .A(_219_),
    .B(_288_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(_220_),
    .B(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__xnor2_1 _372_ (
    .A(_219_),
    .B(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__mux2_1 _373_ (
    .A0(_292_),
    .A1(_220_),
    .S(_288_),
    .X(_226_)
  );
  sky130_fd_sc_hd__maj3_1 _374_ (
    .A(_219_),
    .B(_220_),
    .C(_290_),
    .X(_293_)
  );
  sky130_fd_sc_hd__xnor2_1 _375_ (
    .A(_221_),
    .B(_290_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__xnor2_1 _376_ (
    .A(_293_),
    .B(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__mux2_1 _377_ (
    .A0(_295_),
    .A1(_221_),
    .S(_288_),
    .X(_227_)
  );
  sky130_fd_sc_hd__maj3_1 _378_ (
    .A(_221_),
    .B(_290_),
    .C(_293_),
    .X(_296_)
  );
  sky130_fd_sc_hd__xnor2_1 _379_ (
    .A(_222_),
    .B(_290_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__xnor2_1 _380_ (
    .A(_296_),
    .B(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__mux2_1 _381_ (
    .A0(_298_),
    .A1(_222_),
    .S(_288_),
    .X(_228_)
  );
  sky130_fd_sc_hd__mux2_1 _382_ (
    .A0(_312_),
    .A1(_266_),
    .S(_289_),
    .X(_229_)
  );
  sky130_fd_sc_hd__mux2_1 _383_ (
    .A0(_313_),
    .A1(_312_),
    .S(_289_),
    .X(_230_)
  );
  sky130_fd_sc_hd__mux2_1 _384_ (
    .A0(_314_),
    .A1(_265_),
    .S(_289_),
    .X(_231_)
  );
  sky130_fd_sc_hd__o21ai_0 _385_ (
    .A1(_299_),
    .A2(_289_),
    .B1(_285_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__dfstp_2 _386_ (
    .CLK(clk),
    .D(_319_),
    .Q(DUTY_CYCLE[0]),
    .SET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_320_),
    .Q(DUTY_CYCLE[1]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfstp_2 _388_ (
    .CLK(clk),
    .D(_321_),
    .Q(DUTY_CYCLE[2]),
    .SET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(_322_),
    .Q(DUTY_CYCLE[3]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(counter_debounce[0]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(counter_debounce[1]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(counter_debounce[2]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(counter_debounce[3]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(counter_debounce[4]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(counter_debounce[5]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(counter_debounce[6]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(counter_debounce[7]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(counter_debounce[8]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(counter_debounce[9]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _400_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(counter_debounce[10]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _401_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(counter_debounce[11]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(counter_debounce[12]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _403_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(counter_debounce[13]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _404_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(counter_debounce[14]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _405_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(counter_debounce[15]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(counter_debounce[16]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _407_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(counter_debounce[17]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _408_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(counter_debounce[18]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(clk),
    .D(_001_[19]),
    .Q(counter_debounce[19]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clk),
    .D(_001_[20]),
    .Q(counter_debounce[20]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clk),
    .D(_001_[21]),
    .Q(counter_debounce[21]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clk),
    .D(_001_[22]),
    .Q(counter_debounce[22]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(clk),
    .D(_001_[23]),
    .Q(counter_debounce[23]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clk),
    .D(_001_[24]),
    .Q(counter_debounce[24]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clk),
    .D(_001_[25]),
    .Q(counter_debounce[25]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(clk),
    .D(_001_[26]),
    .Q(counter_debounce[26]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clk),
    .D(_001_[27]),
    .Q(counter_debounce[27]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clk),
    .D(_323_),
    .Q(tmp1),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clk),
    .D(_324_),
    .Q(tmp2),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(clk),
    .D(_325_),
    .Q(tmp3),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _421_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(counter_PWM[0]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _422_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(counter_PWM[1]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _423_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(counter_PWM[2]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _424_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(counter_PWM[3]),
    .RESET_B(_318_)
  );
  sky130_fd_sc_hd__dfrtp_1 _425_ (
    .CLK(clk),
    .D(_326_),
    .Q(tmp4),
    .RESET_B(_318_)
  );
  assign _317_[0] = _316_[0];
  assign OUT_CLK = clk;
  assign _210_ = 1'h0;
  assign _209_ = 1'h0;
  assign _208_ = 1'h0;
  assign _207_ = 1'h0;
  assign _206_ = 1'h0;
  assign _205_ = 1'h0;
  assign _204_ = 1'h0;
  assign _203_ = 1'h0;
  assign _201_ = 1'h0;
  assign _200_ = 1'h0;
  assign _199_ = 1'h0;
  assign _198_ = 1'h0;
  assign _197_ = 1'h0;
  assign _196_ = 1'h0;
  assign _195_ = 1'h0;
  assign _194_ = 1'h0;
  assign _193_ = 1'h0;
  assign _192_ = 1'h0;
  assign _218_ = 1'h0;
  assign _217_ = 1'h0;
  assign _216_ = 1'h0;
  assign _215_ = 1'h0;
  assign _214_ = 1'h0;
  assign _213_ = 1'h0;
  assign _212_ = 1'h0;
  assign _211_ = 1'h0;
  assign _202_ = 1'h0;
  assign _219_ = DUTY_CYCLE[0];
  assign _312_ = tmp1;
  assign _313_ = tmp2;
  assign _237_ = counter_debounce[0];
  assign _248_ = counter_debounce[1];
  assign _258_ = counter_debounce[3];
  assign _257_ = counter_debounce[2];
  assign _259_ = counter_debounce[4];
  assign _260_ = counter_debounce[5];
  assign _262_ = counter_debounce[7];
  assign _261_ = counter_debounce[6];
  assign _264_ = counter_debounce[9];
  assign _263_ = counter_debounce[8];
  assign _239_ = counter_debounce[11];
  assign _238_ = counter_debounce[10];
  assign _241_ = counter_debounce[13];
  assign _240_ = counter_debounce[12];
  assign _243_ = counter_debounce[15];
  assign _242_ = counter_debounce[14];
  assign _245_ = counter_debounce[17];
  assign _244_ = counter_debounce[16];
  assign _246_ = counter_debounce[18];
  assign _247_ = counter_debounce[19];
  assign _249_ = counter_debounce[20];
  assign _250_ = counter_debounce[21];
  assign _252_ = counter_debounce[23];
  assign _251_ = counter_debounce[22];
  assign _254_ = counter_debounce[25];
  assign _253_ = counter_debounce[24];
  assign _256_ = counter_debounce[27];
  assign _255_ = counter_debounce[26];
  assign _220_ = DUTY_CYCLE[1];
  assign _222_ = DUTY_CYCLE[3];
  assign _221_ = DUTY_CYCLE[2];
  assign _315_ = tmp4;
  assign _314_ = tmp3;
  assign _001_[0] = _191_;
  assign _001_[1] = _202_;
  assign _001_[2] = _211_;
  assign _001_[3] = _212_;
  assign _001_[4] = _213_;
  assign _001_[5] = _214_;
  assign _001_[6] = _215_;
  assign _001_[7] = _216_;
  assign _001_[8] = _217_;
  assign _001_[9] = _218_;
  assign _001_[10] = _192_;
  assign _001_[11] = _193_;
  assign _001_[12] = _194_;
  assign _001_[13] = _195_;
  assign _001_[14] = _196_;
  assign _001_[15] = _197_;
  assign _001_[16] = _198_;
  assign _001_[17] = _199_;
  assign _001_[18] = _200_;
  assign _001_[19] = _201_;
  assign _001_[20] = _203_;
  assign _001_[21] = _204_;
  assign _001_[22] = _205_;
  assign _001_[23] = _206_;
  assign _001_[24] = _207_;
  assign _001_[25] = _208_;
  assign _001_[26] = _209_;
  assign _001_[27] = _210_;
  assign _233_ = counter_PWM[0];
  assign _234_ = counter_PWM[1];
  assign _236_ = counter_PWM[3];
  assign _235_ = counter_PWM[2];
  assign _000_[0] = _187_;
  assign _000_[1] = _188_;
  assign _000_[2] = _189_;
  assign _000_[3] = _190_;
  assign PWM_OUT = _223_;
  assign _311_ = reset;
  assign _318_ = _224_;
  assign _319_ = _225_;
  assign _320_ = _226_;
  assign _321_ = _227_;
  assign _322_ = _228_;
  assign _266_ = increase_duty;
  assign _323_ = _229_;
  assign _324_ = _230_;
  assign _265_ = decrease_duty;
  assign _325_ = _231_;
  assign _326_ = _232_;
endmodule
