/* Generated by Yosys 0.26+4 (git sha1 5ea2c290a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module PWM_gen(clk, increase_duty, decrease_duty, reset, PWM_OUT);
  wire [3:0] _000_;
  wire [27:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire [3:0] _353_;
  wire [3:0] _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire [3:0] DUTY_CYCLE;
  output PWM_OUT;
  wire PWM_OUT;
  input clk;
  wire clk;
  wire [3:0] counter_PWM;
  wire [27:0] counter_debounce;
  input decrease_duty;
  wire decrease_duty;
  input increase_duty;
  wire increase_duty;
  input reset;
  wire reset;
  wire slow_clk_enable;
  wire tmp1;
  wire tmp2;
  wire tmp3;
  wire tmp4;
  sky130_fd_sc_hd__clkinv_1 _403_ (
    .A(_349_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__clkinv_1 _404_ (
    .A(_222_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__clkinv_1 _405_ (
    .A(_221_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__clkinv_1 _406_ (
    .A(_220_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__clkinv_1 _407_ (
    .A(_219_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__clkinv_1 _408_ (
    .A(_348_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor4_1 _409_ (
    .A(_303_),
    .B(_285_),
    .C(_290_),
    .D(_293_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nor4_1 _410_ (
    .A(_277_),
    .B(_284_),
    .C(_289_),
    .D(_294_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__nor3_1 _411_ (
    .A(_282_),
    .B(_283_),
    .C(_286_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__and3_1 _412_ (
    .A(_311_),
    .B(_312_),
    .C(_313_),
    .X(_314_)
  );
  sky130_fd_sc_hd__or4_1 _413_ (
    .A(_288_),
    .B(_291_),
    .C(_292_),
    .D(_295_),
    .X(_315_)
  );
  sky130_fd_sc_hd__or4_1 _414_ (
    .A(_299_),
    .B(_301_),
    .C(_278_),
    .D(_281_),
    .X(_316_)
  );
  sky130_fd_sc_hd__nor2_1 _415_ (
    .A(_315_),
    .B(_316_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__or3_1 _416_ (
    .A(_287_),
    .B(_296_),
    .C(_298_),
    .X(_318_)
  );
  sky130_fd_sc_hd__or3_1 _417_ (
    .A(_300_),
    .B(_302_),
    .C(_280_),
    .X(_319_)
  );
  sky130_fd_sc_hd__nor4_1 _418_ (
    .A(_297_),
    .B(_279_),
    .C(_318_),
    .D(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nand2_1 _419_ (
    .A(_317_),
    .B(_320_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__and4_1 _420_ (
    .A(_276_),
    .B(_314_),
    .C(_317_),
    .D(_320_),
    .X(_322_)
  );
  sky130_fd_sc_hd__and4_1 _421_ (
    .A(_276_),
    .B(_314_),
    .C(_317_),
    .D(_320_),
    .X(_323_)
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(_352_),
    .A1(_351_),
    .S(_323_),
    .X(_271_)
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(_351_),
    .A1(_304_),
    .S(_323_),
    .X(_270_)
  );
  sky130_fd_sc_hd__mux2_1 _424_ (
    .A0(_350_),
    .A1(_349_),
    .S(_323_),
    .X(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _425_ (
    .A(_305_),
    .B(_323_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__o21ai_0 _426_ (
    .A1(_306_),
    .A2(_323_),
    .B1(_324_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand2_1 _427_ (
    .A(_308_),
    .B(_309_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__a21oi_1 _428_ (
    .A1(_222_),
    .A2(_325_),
    .B1(_350_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__a21o_1 _429_ (
    .A1(_222_),
    .A2(_325_),
    .B1(_350_),
    .X(_327_)
  );
  sky130_fd_sc_hd__and3_1 _430_ (
    .A(_349_),
    .B(_322_),
    .C(_326_),
    .X(_328_)
  );
  sky130_fd_sc_hd__a31oi_1 _431_ (
    .A1(_349_),
    .A2(_323_),
    .A3(_326_),
    .B1(_309_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__nand4_1 _432_ (
    .A(_349_),
    .B(_309_),
    .C(_323_),
    .D(_326_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__a41oi_1 _433_ (
    .A1(_307_),
    .A2(_308_),
    .A3(_309_),
    .A4(_310_),
    .B1(_352_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__nand3_1 _434_ (
    .A(_351_),
    .B(_322_),
    .C(_331_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__o2111ai_1 _435_ (
    .A1(_306_),
    .A2(_327_),
    .B1(_331_),
    .C1(_322_),
    .D1(_351_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__a2111o_1 _436_ (
    .A1(_219_),
    .A2(_330_),
    .B1(_333_),
    .C1(_329_),
    .D1(_221_),
    .X(_334_)
  );
  sky130_fd_sc_hd__nand3_1 _437_ (
    .A(_220_),
    .B(_219_),
    .C(_328_),
    .Y(_335_)
  );
  sky130_fd_sc_hd__and4_1 _438_ (
    .A(_221_),
    .B(_220_),
    .C(_219_),
    .D(_328_),
    .X(_336_)
  );
  sky130_fd_sc_hd__o21a_1 _439_ (
    .A1(_222_),
    .A2(_336_),
    .B1(_334_),
    .X(_267_)
  );
  sky130_fd_sc_hd__o41ai_1 _440_ (
    .A1(_220_),
    .A2(_219_),
    .A3(_328_),
    .A4(_332_),
    .B1(_221_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__a31oi_1 _441_ (
    .A1(_334_),
    .A2(_335_),
    .A3(_337_),
    .B1(_336_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__xnor3_1 _442_ (
    .A(_309_),
    .B(_219_),
    .C(_328_),
    .X(_338_)
  );
  sky130_fd_sc_hd__nand2b_1 _443_ (
    .A_N(_328_),
    .B(_332_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__mux2i_1 _444_ (
    .A0(_309_),
    .A1(_338_),
    .S(_339_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__xnor2_1 _445_ (
    .A(_310_),
    .B(_339_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor3b_1 _446_ (
    .A(_321_),
    .B(_276_),
    .C_N(_314_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(_272_),
    .B(_273_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__o31a_1 _448_ (
    .A1(_272_),
    .A2(_273_),
    .A3(_274_),
    .B1(_275_),
    .X(_341_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(_272_),
    .B(_341_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__and2_0 _450_ (
    .A(_272_),
    .B(_273_),
    .X(_342_)
  );
  sky130_fd_sc_hd__nor3_1 _451_ (
    .A(_275_),
    .B(_340_),
    .C(_342_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _452_ (
    .A1(_274_),
    .A2(_342_),
    .B1(_275_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__o21a_1 _453_ (
    .A1(_274_),
    .A2(_342_),
    .B1(_343_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _454_ (
    .A(_341_),
    .B(_343_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a211oi_1 _455_ (
    .A1(_309_),
    .A2(_273_),
    .B1(_272_),
    .C1(_310_),
    .Y(_344_)
  );
  sky130_fd_sc_hd__o22ai_1 _456_ (
    .A1(_309_),
    .A2(_273_),
    .B1(_274_),
    .B2(_308_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__a22oi_1 _457_ (
    .A1(_307_),
    .A2(_275_),
    .B1(_274_),
    .B2(_308_),
    .Y(_346_)
  );
  sky130_fd_sc_hd__o21ai_0 _458_ (
    .A1(_344_),
    .A2(_345_),
    .B1(_346_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__o21ai_0 _459_ (
    .A1(_307_),
    .A2(_275_),
    .B1(_347_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__clkinv_1 _460_ (
    .A(_348_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__clkinv_1 _461_ (
    .A(_348_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__clkinv_1 _462_ (
    .A(_348_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__clkinv_1 _463_ (
    .A(_348_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__clkinv_1 _464_ (
    .A(_348_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__clkinv_1 _465_ (
    .A(_348_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__clkinv_1 _466_ (
    .A(_348_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__clkinv_1 _467_ (
    .A(_348_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__clkinv_1 _468_ (
    .A(_348_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__clkinv_1 _469_ (
    .A(_348_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__clkinv_1 _470_ (
    .A(_348_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__clkinv_1 _471_ (
    .A(_348_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__clkinv_1 _472_ (
    .A(_348_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__clkinv_1 _473_ (
    .A(_348_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__clkinv_1 _474_ (
    .A(_348_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__clkinv_1 _475_ (
    .A(_348_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__clkinv_1 _476_ (
    .A(_348_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__clkinv_1 _477_ (
    .A(_348_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__clkinv_1 _478_ (
    .A(_348_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__clkinv_1 _479_ (
    .A(_348_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__clkinv_1 _480_ (
    .A(_348_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__clkinv_1 _481_ (
    .A(_348_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__clkinv_1 _482_ (
    .A(_348_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__clkinv_1 _483_ (
    .A(_348_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__clkinv_1 _484_ (
    .A(_348_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__clkinv_1 _485_ (
    .A(_348_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__clkinv_1 _486_ (
    .A(_348_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__clkinv_1 _487_ (
    .A(_348_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__clkinv_1 _488_ (
    .A(_348_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__clkinv_1 _489_ (
    .A(_348_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__clkinv_1 _490_ (
    .A(_348_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__clkinv_1 _491_ (
    .A(_348_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__clkinv_1 _492_ (
    .A(_348_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__clkinv_1 _493_ (
    .A(_348_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__clkinv_1 _494_ (
    .A(_348_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__clkinv_1 _495_ (
    .A(_348_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__clkinv_1 _496_ (
    .A(_348_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__clkinv_1 _497_ (
    .A(_348_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__clkinv_1 _498_ (
    .A(_348_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__dfstp_2 _499_ (
    .CLK(clk),
    .D(_395_),
    .Q(DUTY_CYCLE[0]),
    .SET_B(_355_)
  );
  sky130_fd_sc_hd__dfrtp_1 _500_ (
    .CLK(clk),
    .D(_396_),
    .Q(DUTY_CYCLE[1]),
    .RESET_B(_356_)
  );
  sky130_fd_sc_hd__dfstp_2 _501_ (
    .CLK(clk),
    .D(_397_),
    .Q(DUTY_CYCLE[2]),
    .SET_B(_357_)
  );
  sky130_fd_sc_hd__dfrtp_1 _502_ (
    .CLK(clk),
    .D(_398_),
    .Q(DUTY_CYCLE[3]),
    .RESET_B(_358_)
  );
  sky130_fd_sc_hd__dfrtp_1 _503_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(counter_debounce[0]),
    .RESET_B(_359_)
  );
  sky130_fd_sc_hd__dfrtp_1 _504_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(counter_debounce[1]),
    .RESET_B(_360_)
  );
  sky130_fd_sc_hd__dfrtp_1 _505_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(counter_debounce[2]),
    .RESET_B(_361_)
  );
  sky130_fd_sc_hd__dfrtp_1 _506_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(counter_debounce[3]),
    .RESET_B(_362_)
  );
  sky130_fd_sc_hd__dfrtp_1 _507_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(counter_debounce[4]),
    .RESET_B(_363_)
  );
  sky130_fd_sc_hd__dfrtp_1 _508_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(counter_debounce[5]),
    .RESET_B(_364_)
  );
  sky130_fd_sc_hd__dfrtp_1 _509_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(counter_debounce[6]),
    .RESET_B(_365_)
  );
  sky130_fd_sc_hd__dfrtp_1 _510_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(counter_debounce[7]),
    .RESET_B(_366_)
  );
  sky130_fd_sc_hd__dfrtp_1 _511_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(counter_debounce[8]),
    .RESET_B(_367_)
  );
  sky130_fd_sc_hd__dfrtp_1 _512_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(counter_debounce[9]),
    .RESET_B(_368_)
  );
  sky130_fd_sc_hd__dfrtp_1 _513_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(counter_debounce[10]),
    .RESET_B(_369_)
  );
  sky130_fd_sc_hd__dfrtp_1 _514_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(counter_debounce[11]),
    .RESET_B(_370_)
  );
  sky130_fd_sc_hd__dfrtp_1 _515_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(counter_debounce[12]),
    .RESET_B(_371_)
  );
  sky130_fd_sc_hd__dfrtp_1 _516_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(counter_debounce[13]),
    .RESET_B(_372_)
  );
  sky130_fd_sc_hd__dfrtp_1 _517_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(counter_debounce[14]),
    .RESET_B(_373_)
  );
  sky130_fd_sc_hd__dfrtp_1 _518_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(counter_debounce[15]),
    .RESET_B(_374_)
  );
  sky130_fd_sc_hd__dfrtp_1 _519_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(counter_debounce[16]),
    .RESET_B(_375_)
  );
  sky130_fd_sc_hd__dfrtp_1 _520_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(counter_debounce[17]),
    .RESET_B(_376_)
  );
  sky130_fd_sc_hd__dfrtp_1 _521_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(counter_debounce[18]),
    .RESET_B(_377_)
  );
  sky130_fd_sc_hd__dfrtp_1 _522_ (
    .CLK(clk),
    .D(_001_[19]),
    .Q(counter_debounce[19]),
    .RESET_B(_378_)
  );
  sky130_fd_sc_hd__dfrtp_1 _523_ (
    .CLK(clk),
    .D(_001_[20]),
    .Q(counter_debounce[20]),
    .RESET_B(_379_)
  );
  sky130_fd_sc_hd__dfrtp_1 _524_ (
    .CLK(clk),
    .D(_001_[21]),
    .Q(counter_debounce[21]),
    .RESET_B(_380_)
  );
  sky130_fd_sc_hd__dfrtp_1 _525_ (
    .CLK(clk),
    .D(_001_[22]),
    .Q(counter_debounce[22]),
    .RESET_B(_381_)
  );
  sky130_fd_sc_hd__dfrtp_1 _526_ (
    .CLK(clk),
    .D(_001_[23]),
    .Q(counter_debounce[23]),
    .RESET_B(_382_)
  );
  sky130_fd_sc_hd__dfrtp_1 _527_ (
    .CLK(clk),
    .D(_001_[24]),
    .Q(counter_debounce[24]),
    .RESET_B(_383_)
  );
  sky130_fd_sc_hd__dfrtp_1 _528_ (
    .CLK(clk),
    .D(_001_[25]),
    .Q(counter_debounce[25]),
    .RESET_B(_384_)
  );
  sky130_fd_sc_hd__dfrtp_1 _529_ (
    .CLK(clk),
    .D(_001_[26]),
    .Q(counter_debounce[26]),
    .RESET_B(_385_)
  );
  sky130_fd_sc_hd__dfrtp_1 _530_ (
    .CLK(clk),
    .D(_001_[27]),
    .Q(counter_debounce[27]),
    .RESET_B(_386_)
  );
  sky130_fd_sc_hd__dfrtp_1 _531_ (
    .CLK(clk),
    .D(_399_),
    .Q(tmp1),
    .RESET_B(_387_)
  );
  sky130_fd_sc_hd__dfrtp_1 _532_ (
    .CLK(clk),
    .D(_400_),
    .Q(tmp2),
    .RESET_B(_388_)
  );
  sky130_fd_sc_hd__dfrtp_1 _533_ (
    .CLK(clk),
    .D(_401_),
    .Q(tmp3),
    .RESET_B(_389_)
  );
  sky130_fd_sc_hd__dfrtp_1 _534_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(counter_PWM[0]),
    .RESET_B(_390_)
  );
  sky130_fd_sc_hd__dfrtp_1 _535_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(counter_PWM[1]),
    .RESET_B(_391_)
  );
  sky130_fd_sc_hd__dfrtp_1 _536_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(counter_PWM[2]),
    .RESET_B(_392_)
  );
  sky130_fd_sc_hd__dfrtp_1 _537_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(counter_PWM[3]),
    .RESET_B(_393_)
  );
  sky130_fd_sc_hd__dfrtp_1 _538_ (
    .CLK(clk),
    .D(_402_),
    .Q(tmp4),
    .RESET_B(_394_)
  );
  assign _354_[0] = _353_[0];
  assign _210_ = 1'h0;
  assign _209_ = 1'h0;
  assign _208_ = 1'h0;
  assign _207_ = 1'h0;
  assign _206_ = 1'h0;
  assign _205_ = 1'h0;
  assign _204_ = 1'h0;
  assign _203_ = 1'h0;
  assign _201_ = 1'h0;
  assign _200_ = 1'h0;
  assign _199_ = 1'h0;
  assign _198_ = 1'h0;
  assign _197_ = 1'h0;
  assign _196_ = 1'h0;
  assign _195_ = 1'h0;
  assign _194_ = 1'h0;
  assign _193_ = 1'h0;
  assign _192_ = 1'h0;
  assign _218_ = 1'h0;
  assign _217_ = 1'h0;
  assign _216_ = 1'h0;
  assign _215_ = 1'h0;
  assign _214_ = 1'h0;
  assign _213_ = 1'h0;
  assign _212_ = 1'h0;
  assign _211_ = 1'h0;
  assign _202_ = 1'h0;
  assign _352_ = tmp4;
  assign _351_ = tmp3;
  assign _402_ = _271_;
  assign _304_ = decrease_duty;
  assign _401_ = _270_;
  assign _350_ = tmp2;
  assign _349_ = tmp1;
  assign _400_ = _269_;
  assign _305_ = increase_duty;
  assign _399_ = _268_;
  assign _222_ = DUTY_CYCLE[3];
  assign _398_ = _267_;
  assign _221_ = DUTY_CYCLE[2];
  assign _397_ = _266_;
  assign _220_ = DUTY_CYCLE[1];
  assign _396_ = _265_;
  assign _219_ = DUTY_CYCLE[0];
  assign _395_ = _264_;
  assign _276_ = counter_debounce[0];
  assign _287_ = counter_debounce[1];
  assign _297_ = counter_debounce[3];
  assign _296_ = counter_debounce[2];
  assign _298_ = counter_debounce[4];
  assign _299_ = counter_debounce[5];
  assign _301_ = counter_debounce[7];
  assign _300_ = counter_debounce[6];
  assign _303_ = counter_debounce[9];
  assign _302_ = counter_debounce[8];
  assign _278_ = counter_debounce[11];
  assign _277_ = counter_debounce[10];
  assign _280_ = counter_debounce[13];
  assign _279_ = counter_debounce[12];
  assign _282_ = counter_debounce[15];
  assign _281_ = counter_debounce[14];
  assign _284_ = counter_debounce[17];
  assign _283_ = counter_debounce[16];
  assign _285_ = counter_debounce[18];
  assign _286_ = counter_debounce[19];
  assign _288_ = counter_debounce[20];
  assign _289_ = counter_debounce[21];
  assign _291_ = counter_debounce[23];
  assign _290_ = counter_debounce[22];
  assign _293_ = counter_debounce[25];
  assign _292_ = counter_debounce[24];
  assign _295_ = counter_debounce[27];
  assign _294_ = counter_debounce[26];
  assign _001_[0] = _191_;
  assign _001_[1] = _202_;
  assign _001_[2] = _211_;
  assign _001_[3] = _212_;
  assign _001_[4] = _213_;
  assign _001_[5] = _214_;
  assign _001_[6] = _215_;
  assign _001_[7] = _216_;
  assign _001_[8] = _217_;
  assign _001_[9] = _218_;
  assign _001_[10] = _192_;
  assign _001_[11] = _193_;
  assign _001_[12] = _194_;
  assign _001_[13] = _195_;
  assign _001_[14] = _196_;
  assign _001_[15] = _197_;
  assign _001_[16] = _198_;
  assign _001_[17] = _199_;
  assign _001_[18] = _200_;
  assign _001_[19] = _201_;
  assign _001_[20] = _203_;
  assign _001_[21] = _204_;
  assign _001_[22] = _205_;
  assign _001_[23] = _206_;
  assign _001_[24] = _207_;
  assign _001_[25] = _208_;
  assign _001_[26] = _209_;
  assign _001_[27] = _210_;
  assign _272_ = counter_PWM[0];
  assign _273_ = counter_PWM[1];
  assign _275_ = counter_PWM[3];
  assign _274_ = counter_PWM[2];
  assign _000_[0] = _187_;
  assign _000_[1] = _188_;
  assign _000_[2] = _189_;
  assign _000_[3] = _190_;
  assign PWM_OUT = _223_;
  assign _348_ = reset;
  assign _355_ = _224_;
  assign _356_ = _225_;
  assign _357_ = _226_;
  assign _358_ = _227_;
  assign _359_ = _228_;
  assign _360_ = _229_;
  assign _361_ = _230_;
  assign _362_ = _231_;
  assign _363_ = _232_;
  assign _364_ = _233_;
  assign _365_ = _234_;
  assign _366_ = _235_;
  assign _367_ = _236_;
  assign _368_ = _237_;
  assign _369_ = _238_;
  assign _370_ = _239_;
  assign _371_ = _240_;
  assign _372_ = _241_;
  assign _373_ = _242_;
  assign _374_ = _243_;
  assign _375_ = _244_;
  assign _376_ = _245_;
  assign _377_ = _246_;
  assign _378_ = _247_;
  assign _379_ = _248_;
  assign _380_ = _249_;
  assign _381_ = _250_;
  assign _382_ = _251_;
  assign _383_ = _252_;
  assign _384_ = _253_;
  assign _385_ = _254_;
  assign _386_ = _255_;
  assign _387_ = _256_;
  assign _388_ = _257_;
  assign _389_ = _258_;
  assign _390_ = _259_;
  assign _391_ = _260_;
  assign _392_ = _261_;
  assign _393_ = _262_;
  assign _394_ = _263_;
endmodule
